Zinkal changes
vish1406/exchange-admin-panel pull request #111
Opened 2023-12-18 06:38 UTC by zdthakker-dev

user-history bug,logged-in client page and dashboard icon.

2023-12-18 15:51 UTC, ca-pikachu requested changes
@zdthakker-dev Please resolve the conflicts and the requested changes

2023-12-18 15:51 UTC, ca-pikachu commented on src/Pages/Account/LoggedInUsers/LoggedInUsers.jsx
> +  ].filter(Boolean);
Why are we filtering this?

2023-12-18 15:51 UTC, ca-pikachu commented on src/Pages/Account/LoggedInUsers/LoggedInUsers.jsx
> +    setData([]);
`setData([])` is already called in the cleanup function so we can remove it from here.

2023-12-18 15:51 UTC, ca-pikachu commented on src/Pages/Account/LoggedInUsers/LoggedInUsers.jsx
> +    if (searchQuery !== "") {
I've added a comment for this change in the `UserActivity.jsx` 
We can go with the same flow here.

2023-12-19 04:42 UTC, zdthakker-dev commented on src/Pages/Dashboard/Dashboard/Dashboard.jsx
> +                {/* <Link to="/logged-in-users"> */}
yes

2023-12-20 08:11 UTC, ca-pikachu approved these changes

2023-12-21 04:38 UTC, merged